paths:
  /products:
    get:
      security:
      - bearerAuth: []
      tags:
      - Products
      summary: Lista de productos.
      responses:
        200:
          description: Se genero listado de productos correctamente.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/registerNew'
        500:
          description: Error de servidor.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/notFound'
        404:
          description: Error de validacion del schema.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/validationError'
    post:
      security:
      - bearerAuth: []
      tags:
      - Products
      summary: Registro de nuevo producto.
      requestBody:
        content:
          application/json:
              type: object
              required:
                - code
                - title
                - description
                - price
                - thumbnail
                - stock
                - category
                - status
              properties:
                code:
                  type: string
                  description: Codigo unico
                title:
                  type: string
                  description: Titulo de producto
                description:
                  type: string
                  description: Descripcion de producto
                price:
                  type: number
                  description: Precio de producto
                thumbnail:
                  type: array
                  items:
                      type: string
                  description: Thumbnails de producto
                stock:
                  type: integer
                  description: Stock de producto
                category:
                  type: string
                  description: Categoria de producto
                status:
                  type: boolean
                  description: status de producto
              example:
                code: ctfk1k
                title: Keyboard
                description: Electronic Concrete Chicken
                price: 586.00
                thumbnail: ["https://via.placeholder.com/580x3890/4bdb4d/53652d.png?text=tricesimus%20cunabula%20virga",
                            "https://via.placeholder.com/1497x1169/b21509/ae57fc.png?text=subito%20admoveo%20arguo"]
                stock: 50
                category: Books
                status: true
      responses:
        200:
          description: Se registró producto correctamente.
  /products/{pid}:  
    get:
      security:
      - bearerAuth: []
      tags:
      - Products
      summary: Obtiene producto por Id.
      parameters:
        - in: path
          name: pid
          required: true
          description: id de producto.
          schema:
            type: string
      responses:
        200: 
          description: Producto obtenido correctamente.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/getAllNews'
    put:
      security:
      - bearerAuth: []
      tags:
      - Products
      summary: Actualiza producto por Id.
      parameters:
        - in: path
          name: pid
          required: true
          description: id de producto.
          schema:
            type: string
      requestBody:
        content:
          application/json:
              type: object
              required:
                - code
                - title
                - description
                - price
                - thumbnail
                - stock
                - category
                - status
              properties:
                code:
                  type: string
                  description: Codigo unico
                title:
                  type: string
                  description: Titulo de producto
                description:
                  type: string
                  description: Descripcion de producto
                price:
                  type: number
                  description: Precio de producto
                thumbnail:
                  type: array
                  items:
                      type: string
                  description: Thumbnails de producto
                stock:
                  type: integer
                  description: Stock de producto
                category:
                  type: string
                  description: Categoria de producto
                status:
                  type: boolean
                  description: status de producto
              example:
                code: ctfk1k
                title: Keyboard
                description: Electronic Concrete Chicken
                price: 586.00
                thumbnail: ["https://via.placeholder.com/580x3890/4bdb4d/53652d.png?text=tricesimus%20cunabula%20virga",
                            "https://via.placeholder.com/1497x1169/b21509/ae57fc.png?text=subito%20admoveo%20arguo"]
                stock: 50
                category: Books
                status: true
      responses:
        200: 
          description: Producto actualizado correctamente.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/getAllNews'
    delete:
      security:
      - bearerAuth: []
      tags:
      - Products
      summary: Elimina producto por Id.
      parameters:
        - in: path
          name: pid
          required: true
          description: id de producto.
          schema:
            type: string
      responses:
        200: 
          description: Producto eliminado correctamente.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/getAllNews'
  /products/mocks/mockingProducts:  
    get:
      security:
      - bearerAuth: []
      tags:
      - Products
      summary: Obtiene mock de productos.
      responses:
        200: 
          description: Listado de productos obtenido correctamente.
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schema/News/getAllNews'
